name: Frontend CI

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'client/**'
      - '.github/workflows/frontend-ci.yml'
  push:
    branches: [ main, develop ]
    paths:
      - 'client/**'
      - '.github/workflows/frontend-ci.yml'

jobs:
  frontend-ci:
    name: Frontend - Install, Build & Run
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json
      
      - name: Install dependencies
        working-directory: ./client
        run: |
          echo "📦 Installing dependencies..."
          npm ci
          echo "✅ Installation successful"
      
      - name: Build
        working-directory: ./client
        run: |
          echo "🔨 Building frontend..."
          npm run build
          echo "✅ Build successful"
      
      - name: Verify build output
        working-directory: ./client
        run: |
          echo "📂 Verifying build artifacts..."
          ls -la dist/
          echo "✅ Build artifacts verified"
      
      - name: Summary
        if: success()
        run: |
          echo "=================================="
          echo "✅ Frontend CI Passed"
          echo "=================================="
          echo "All frontend checks completed successfully!"
